/* Generated by           cobc 3.1.2.0 */
/* Generated from         ler.cob */
/* Generated at           jun 26 2025 13:44:08 */
/* GnuCOBOL build date    Apr 14 2024 07:59:15 */
/* GnuCOBOL package date  Dec 23 2020 12:04:58 UTC */
/* Compile command        cobc -C -save-temp -Wall ler.cob */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x1000, NULL};
static const cob_field_attr a_2 =	{0x10,   3,   0, 0x0000, NULL};
static const cob_field_attr a_3 =	{0x10,   4,   0, 0x0000, NULL};


/* Constants */
static const cob_field c_1	= {27, (cob_u8_ptr)"Digite o primeiro n\303\272mero: ", &a_1};
static const cob_field c_2	= {26, (cob_u8_ptr)"Digite o segundo n\303\272mero: ", &a_1};
static const cob_field c_3	= {6, (cob_u8_ptr)"Soma: ", &a_1};
static const cob_field c_4	= {18, (cob_u8_ptr)"Primeiro \303\251 maior.", &a_1};
static const cob_field c_5	= {26, (cob_u8_ptr)"Segundo \303\251 maior ou igual.", &a_1};

