/* Generated by           cobc 3.1.2.0 */
/* Generated from         ler.cob */
/* Generated at           jun 26 2025 13:44:08 */
/* GnuCOBOL build date    Apr 14 2024 07:59:15 */
/* GnuCOBOL package date  Dec 23 2020 12:04:58 UTC */
/* Compile command        cobc -C -save-temp -Wall ler.cob */

#include <stdio.h>
#include <string.h>
#define  COB_KEYWORD_INLINE __inline
#include <gmp.h>
#include <libcob.h>

#define  COB_SOURCE_FILE		"ler.cob"
#define  COB_PACKAGE_VERSION		"3.1.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"jun 26 2025 13:44:08"
#define  COB_MODULE_DATE		20250626
#define  COB_MODULE_TIME		134408

/* Global variables */
#include "ler.c.h"

/* Function prototypes */

int		ler (void);
static int		ler_ (const int);
static void		ler_module_init (cob_module *module);

/* Functions */

/* PROGRAM-ID 'ler' */

/* ENTRY 'ler' */

int
ler ()
{
  return ler_ (0);
}

static int
ler_ (const int entry)
{
  /* Program local variables */
  #include "ler.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Allocate decimal numbers */
  cob_decimal_alloc (2, &d0, &d1);

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 10        : Entry     ler                     : ler.cob */
  l_2:;

  /* Line: 11        : DISPLAY            : ler.cob */
  cob_display (0, 1, 1, &c_1);

  /* Line: 12        : ACCEPT             : ler.cob */
  cob_accept (&f_8);

  /* Line: 14        : DISPLAY            : ler.cob */
  cob_display (0, 1, 1, &c_2);

  /* Line: 15        : ACCEPT             : ler.cob */
  cob_accept (&f_9);

  /* Line: 17        : COMPUTE            : ler.cob */
  cob_decimal_set_field (d0, &f_8);
  cob_decimal_set_field (d1, &f_9);
  cob_decimal_add (d0, d1);
  cob_decimal_get_field (d0, &f_10, 0);

  /* Line: 18        : DISPLAY            : ler.cob */
  cob_display (0, 1, 2, &c_3, &f_10);

  /* Line: 20        : IF                 : ler.cob */
  if (((int)memcmp (b_8, b_9, 3) > 0))
  {

    /* Line: 21        : DISPLAY            : ler.cob */
    cob_display (0, 1, 1, &c_4);
  }
  else
  {
    /* ELSE */

    /* Line: 23        : DISPLAY            : ler.cob */
    cob_display (0, 1, 1, &c_5);
  }

  /* Line: 26        : STOP RUN           : ler.cob */
  cob_stop_run (b_2);

  /* Program exit */

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);

  ler_module_init (module);

  module->crt_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  b_2 = 0;
  memset (b_8, 48, 3);
  memset (b_9, 48, 3);
  memset (b_10, 48, 4);

  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  b_2 = 0;
  cob_module_free (&module);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'ler' */

/* Initialize module structure for ler */
static void ler_module_init (cob_module *module)
{
  module->module_name = "ler";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->module_entry.funcptr = (void *(*)())ler;
  module->module_cancel.funcptr = (void *(*)())ler_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 0;
  module->flag_main = 0;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->module_stmt = 0;
  module->module_sources = NULL;
}

/* End functions */

