/* Generated by           cobc 3.1.2.0 */
/* Generated from         ler.cob */
/* Generated at           jun 26 2025 13:44:08 */
/* GnuCOBOL build date    Apr 14 2024 07:59:15 */
/* GnuCOBOL package date  Dec 23 2020 12:04:58 UTC */
/* Compile command        cobc -C -save-temp -Wall ler.cob */

/* Program local variables for 'ler' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;

/* Decimal structures */
cob_decimal	*d0 = NULL;
cob_decimal	*d1 = NULL;


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_8[3] __attribute__((aligned));	/* NUM1 */
static cob_u8_t	b_9[3] __attribute__((aligned));	/* NUM2 */
static cob_u8_t	b_10[4] __attribute__((aligned));	/* RESULT */

/* End of local data storage */


/* Fields (local) */
static cob_field f_8	= {3, b_8, &a_2};	/* NUM1 */
static cob_field f_9	= {3, b_9, &a_2};	/* NUM2 */
static cob_field f_10	= {4, b_10, &a_3};	/* RESULT */

/* End of fields */

